In [1]:
import tensorflow as tf
import numpy as np

# How to create tensor

## from numpy

In [20]:
tensor1=tf.convert_to_tensor(1.5*np.ones((2,2)),dtype=tf.float32) # we specify the dtype in the convert_to_tensor() method
print(tensor1)
print("\nThe values in the tensor")
print(tensor1.numpy())

tensor2=tf.convert_to_tensor(np.zeros((2,4)))
print('\ntensor2\n',tensor2)
print('\nThe values in tensor2\n',tensor2.numpy())

tf.Tensor(
[[1.5 1.5]
 [1.5 1.5]], shape=(2, 2), dtype=float32)

The values in the tensor
[[1.5 1.5]
 [1.5 1.5]]

tensor2
 tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float64)

The values in tensor2
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## from list

In [26]:
tensor1=tf.convert_to_tensor([1,2])
print('\ntensor1\n',tensor1)
print('\nthe values in tensor1\n',tensor1.numpy())

tensor2=tf.convert_to_tensor([[1,2],[3,4]])
print('\n tensor2\n',tensor2)
print('\n the values of tensor2\n',tensor2.numpy())

tensor3=tf.convert_to_tensor([[1],[2]])
print('\n tensor3\n',tensor3)
print('\n the values of tensor3\n',tensor3.numpy())


tensor1
 tf.Tensor([1 2], shape=(2,), dtype=int32)

the values in tensor1
 [1 2]

 tensor2
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

 the values of tensor2
 [[1 2]
 [3 4]]

 tensor3
 tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)

 the values of tensor3
 [[1]
 [2]]


## 将tensor初始化全部为零

In [27]:
# 初始化为一个scalar 0
tensor1=tf.zeros([])
print(tensor1)

tf.Tensor(0.0, shape=(), dtype=float32)


In [28]:
# 初始化一个vector 0
tensor2=tf.zeros([1])# 1 表示shape
print(tensor2)

tf.Tensor([0.], shape=(1,), dtype=float32)


In [31]:
tensor3=tf.zeros_like(tensor3) # create a zero tensor based on the previously tensor3
print(tensor)

tf.Tensor(
[[0]
 [0]], shape=(2, 1), dtype=int32)


## 将tensor全部初始化为1

In [33]:
# 初始化一个scalar 1
tensor1=tf.ones([])
print(tensor1)

tf.Tensor(1.0, shape=(), dtype=float32)


In [34]:
# 初始化一个向量1
tensor2=tf.ones([2])
print(tensor2)

tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [35]:
# 初始化一个ones_like
tensor3=tf.ones_like(tensor3)
print(tensor3)

tf.Tensor(
[[1]
 [1]], shape=(2, 1), dtype=int32)


## fill 函数

In [36]:
tensor1=tf.fill([3,4],3.0)
print(tensor1)

tf.Tensor(
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]], shape=(3, 4), dtype=float32)


## Normal利用正态分布初始化参数

In [39]:
tensor1=tf.random.normal([2,3],mean=1,stddev=1)
print(tensor1.numpy())

[[-0.47074926  0.806013    3.4872637 ]
 [ 1.9491398  -1.2811301   0.75439274]]


In [41]:
tensor1=tf.random.normal([2,3]) # 未指定参数，按照标准正态分布产生
print(tensor1.numpy())

[[ 0.33490542  0.8289524  -0.7614883 ]
 [ 0.26193872  0.67142373 -0.19508004]]


In [42]:
# tf.random.truncated_normal 截断正态分布，当数据大于某个值时，重新采样，防止生成的有的sample 距离中心太远
tensor2=tf.random.truncated_normal([2,3])
print(tensor2.numpy())

[[-0.36331737  1.2414317  -0.2524041 ]
 [ 0.32557806  1.0882075   0.3530345 ]]


## Uniform 利用均匀分布初始化参数

In [43]:
tensor1=tf.random.uniform([2,3],minval=0,maxval=1)
print(tensor1.numpy())

[[0.04177165 0.45704508 0.7888428 ]
 [0.33540547 0.23157287 0.68474686]]


In [44]:
tensor2=tf.random.uniform([3,4],minval=-1,maxval=100)
print(tensor2.numpy())

[[64.42587   -0.2563529  3.3353648 54.858273 ]
 [21.343884  14.795409  36.894142  45.055805 ]
 [18.999464  64.08079   46.417076  51.958584 ]]


In [45]:
## Random Permutation-- tf.random.shuffle
idx=tf.range(10)
print('idx',idx)

idx tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [46]:
# shuffle the idx
shuffledIdx=tf.random.shuffle(idx)
print(shuffledIdx)

tf.Tensor([6 0 3 1 5 2 7 9 4 8], shape=(10,), dtype=int32)


In [49]:
a=tf.random.truncated_normal([10,28,28,3],mean=128,stddev=50)

## Loss 的测试

In [5]:
# generate 4 samples belongs to 10 categories
Xs=tf.random.truncated_normal([4,10]) #mean=0, stddev=1.0

In [8]:
# generate the actual labels for these 4 samples
ys=np.arange(4)

In [11]:
# one-hot methods to generate lables
y=tf.one_hot(ys,depth=10)

In [22]:
# calculate the mse based on the tf.keras.losses.mse
mse=tf.keras.losses.mse(Xs,y) # 表示每个样本的mse

In [26]:
#loss
loss=tf.reduce_mean(mse) #表示所有样本的平均mse
print(loss)

tf.Tensor(1.1791319, shape=(), dtype=float32)


## Matrix 的测试

In [28]:
# generate 4 个28x28的图片，然后打平
Xs=tf.random.truncated_normal([4,784])
print(Xs.numpy())

[[ 1.3723129  -0.3445495  -1.5297327  ... -0.10125105  0.95442164
  -0.31371096]
 [ 0.35457274 -1.4406008   0.01184261 ... -0.12961417  1.2603388
   1.3969551 ]
 [-0.50400126  0.49529934  0.3283863  ... -1.6665027  -1.5839794
   0.8271543 ]
 [ 1.1912068   0.8059943   1.5361724  ...  1.9040502   1.4900529
  -1.1007105 ]]


In [35]:
# Dense layer
denseLayer=tf.keras.layers.Dense(10)
denseLayer.build((4,784))

In [42]:
# 将Xs转换为10个类别
output=denseLayer(Xs)

In [43]:
print(output.numpy())

[[-0.48859018  0.02999738  1.6680865   0.1848881   0.18415484 -0.63987315
   0.43685323 -0.5451695   0.02915066 -2.2275724 ]
 [ 0.3163087   0.83682144  0.48708466 -0.56299406  0.47148082  0.58217895
   0.1167607   0.316918   -0.83765185 -0.5392237 ]
 [-1.5947502   0.6691804   0.5477969  -1.3548672  -1.6124613  -0.93344253
  -0.0954574   1.6042051   0.21826443  0.12334912]
 [-0.6414008   1.2928023  -0.9172078  -1.2385048   0.07280216  2.4834504
  -1.7627219  -0.4878604  -0.44336545  1.2332186 ]]


In [45]:
print(denseLayer.bias.numpy())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [47]:
print(denseLayer.kernel.numpy())

[[-0.05280245 -0.03019325  0.02043037 ... -0.07105641 -0.04426609
  -0.04560211]
 [ 0.03138369  0.01584027  0.01358347 ... -0.07504599 -0.0389759
   0.02871177]
 [-0.06796659 -0.02470696  0.06091861 ... -0.07530548 -0.01748697
   0.06898249]
 ...
 [-0.05194361 -0.07345114  0.01165715 ...  0.04711678 -0.01214118
   0.00355793]
 [ 0.02003109 -0.01493403 -0.05764304 ...  0.07448258 -0.07068512
  -0.0868784 ]
 [ 0.05165536  0.06555247 -0.01674966 ... -0.05723902  0.02110045
   0.0302215 ]]


## Tensor 的索引与切片

In [48]:
# basic indexing [][]
a=tf.ones((1,5,5,3))
print(a)

tf.Tensor(
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]], shape=(1, 5, 5, 3), dtype=float32)


In [49]:
print(a[0][0])

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [57]:
print(a[0][4])

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [63]:
a=tf.random.normal([4,28,28,3])
print(a[0].shape)
print(a[1,2].shape) # 第二个图片的第3行
print(a[1,2,3]) # 第二个图片，第3行，第4列 的元素
print(a[1,2,3].shape)

(28, 28, 3)
(28, 3)
tf.Tensor([-1.6009268   0.38413453  0.2426789 ], shape=(3,), dtype=float32)
(3,)


In [64]:
b=np.array([[[[0,1,2],[2,3,4]],[[5,6,7],[8,9,10]]]])

In [67]:
print(b[0][0][0]) #第一张图片的，第一行，第一列元素
print(b[0][0][1]) #第一张图片的，第一行，第二列元素

[0 1 2]
[2 3 4]


## ...采样方式：通常表示维度很多时，剩下所有的维度

In [78]:
a=tf.random.normal([2,4,28,28,3]) #有2个task,每个batch有4张图片，每个图片是28X28的3通道图像
print('第一个task的大小',a[0].shape)
print('另一种方法',a[0,:,:,:,:].shape)
print('另一种方法',a[0,...].shape)
print('输出红色通道的维度',a[:,:,:,:,0].shape)
print('另一种方法，输出红色通道的维度',a[...,0].shape)
print('输出第1个task的绿色通道的维度',a[0,...,1].shape)
print('输出第1个task,第1个图片红色通道的维度',a[0,0,...,0].shape)

第一个task的大小 (4, 28, 28, 3)
另一种方法 (4, 28, 28, 3)
另一种方法 (4, 28, 28, 3)
输出红色通道的维度 (2, 4, 28, 28)
另一种方法，输出红色通道的维度 (2, 4, 28, 28)
输出第1个task的绿色通道的维度 (4, 28, 28)
输出第1个task,第1个图片红色通道的维度 (28, 28)


## Selective Indexing

In [90]:
# tf.gather 给出一个索引List,然后根据这个list来收集相应元素
a=np.random.randint(0,100,size=(4,35,8)) # a 表示有4个班级的35个学生8门课的成绩

(35, 8)

In [92]:
classLvlGrade=tf.gather(a,axis=0,indices=[2,3]) # a表示数据源，axis表示所取数据的维度，axis=0表示要取班级维度，indices表示索取班级的编号

In [95]:
studLvlGrade=tf.gather(a,axis=1,indices=[16,7,3,9,6]) #在每个班级内选取5个学生，查看成绩
print(studLvlGrade.shape)
print(studLvlGrade)

(4, 5, 8)
tf.Tensor(
[[[73 68 44 63 56 82 50 69]
  [33 19 61 21 49 38 78  3]
  [29 99  8 57 87 50 75 60]
  [89 50 64 21 48 12 97 17]
  [ 9 64 69 56 71 46 18 15]]

 [[18  2 84 72 39 14 75 55]
  [92 97 25 17 28 83 12 32]
  [64 72 11 18 46 76 29 25]
  [ 0 85  3  9 34 79 30 21]
  [37 28 26 65 85 73 55  6]]

 [[ 8 37  2 79 85  1 97 23]
  [ 4 97 78  0 22 78 10 46]
  [56 51 29 30 27  5 88 63]
  [88 71 42 19 64 10 27 15]
  [95 22 42 90 47 81 79 58]]

 [[86 49 78 15 32 73 39 85]
  [15 24 22 39 48 12 19 42]
  [57 44 46 42 34 81  5 30]
  [93  3 68 45 26 63 66 74]
  [ 6 38  6 10 53 55 22 28]]], shape=(4, 5, 8), dtype=int32)


In [98]:
# 查看每个班级，每个学生的特定几门课的成绩
CourseLvlGrade=tf.gather(a,axis=2,indices=[3,5,7])
print(CourseLvlGrade.shape)
# print(CourseLvlGrade)

(4, 35, 3)


In [100]:
# 如何对取特定的几个学生的特定几门课的成绩，用两个gather 串联起来，如第一个gather 取某几个学生在所有课程上的成绩，然后再在这个结果上应用另一个gather对课程操作
studLvlGrade=tf.gather(a,axis=1,indices=[6,4,3,2]) #取编号为7，5，4，3的学生在所有课程上的成绩
print(studLvlGrade.shape)
courseStudLvlGrade=tf.gather(studLvlGrade,axis=2,indices=[3,2,6]) #取该4位学生在课程编号为4，3，7上的成绩
print(courseStudLvlGrade)

(4, 4, 8)
tf.Tensor(
[[[56 69 18]
  [94 46 82]
  [57  8 75]
  [90  9 28]]

 [[65 26 55]
  [19 46 32]
  [18 11 29]
  [43 61 46]]

 [[90 42 79]
  [84 29 83]
  [30 29 88]
  [14 98 36]]

 [[10  6 22]
  [58 35 55]
  [42 46  5]
  [20 58 85]]], shape=(4, 4, 3), dtype=int32)


In [103]:
# tf.gather_nd,能同时指定两个axis,返回这两个axis组合下的值
# 如果想得到第一个班级里第10名学生的成绩
stud10Grade=tf.gather_nd(a,[0,9])
print(stud10Grade.shape)
print(stud10Grade)
#返回第二个班级里，第4个学生在第三门课上的成绩
g=tf.gather_nd(a,[1,3,2])
print(g)
g1=tf.gather_nd(a,[[1,3,2]])
print(g1)

(8,)
tf.Tensor([89 50 64 21 48 12 97 17], shape=(8,), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor([11], shape=(1,), dtype=int32)


In [106]:
# 一次性返回第一个班级的第一个学生和第二班级的第3号学生在所有科目上的学习成绩
g=tf.gather_nd(a,[[0,1],[1,2]])
print(g)
g=tf.gather_nd(a,[[0,0],[1,1],[2,2],[3,3]])
print(g)
g=tf.gather_nd(a,[[0,0,0],[1,1,1],[2,2,2],[3,3,3]])# 第1号班级第一号学生第一门课的成绩，依次类推。。。
print(g)

tf.Tensor(
[[57 99 55 57 22  2 19 68]
 [97 14 61 43 38 75 46 27]], shape=(2, 8), dtype=int32)
tf.Tensor(
[[84 45  7 80 78 13 64 23]
 [26 32 97 92 58 45 66 16]
 [27 47 98 14  2  6 36 89]
 [57 44 46 42 34 81  5 30]], shape=(4, 8), dtype=int32)
tf.Tensor([84 32 98 42], shape=(4,), dtype=int32)


## tf.boolean_mask 的用法

In [111]:
# 取出矩阵中特定的数
a=tf.random.normal([4,28,28,3]) # 4 个28x28的彩色图像
#取第一张和第三张图像
a1=tf.boolean_mask(a,mask=[True,True,False,False])
print(a1.shape)
# 取所有图像的红色通道上的值
a=tf.boolean_mask(a,mask=[True,False,False],axis=3) #mask 的长度必须对应于该轴的长度
print(a.shape)

(2, 28, 28, 3)
(4, 28, 28, 1)


In [113]:
a=tf.ones([2,3,4])
print(a)
print()
print(tf.boolean_mask(a,mask=[[True,False,True],[False,True,False]]))

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


## 维度变换

In [114]:
# tf.reshape(a,...)
# tf.transpose()

In [117]:
a=tf.random.normal((4,3,2,1))
print(a.shape)

(4, 3, 2, 1)


In [119]:
tf.transpose(a).shape

TensorShape([1, 2, 3, 4])

In [121]:
tf.transpose(a,perm=[0,1,3,2]) # 将axis=2 的数据和 axis=3的数据进行转置

<tf.Tensor: id=844, shape=(4, 3, 1, 2), dtype=float32, numpy=
array([[[[-1.0050664 , -0.7282231 ]],

        [[ 1.4444928 ,  0.42903435]],

        [[ 1.0758896 , -0.15058401]]],


       [[[-1.4601474 , -0.13727722]],

        [[-0.6990763 , -1.8261116 ]],

        [[-1.215721  , -0.14686827]]],


       [[[ 0.04413291, -1.2327082 ]],

        [[-2.3393779 ,  0.9265482 ]],

        [[-0.3005892 ,  0.9553196 ]]],


       [[[ 1.6178818 ,  1.4105822 ]],

        [[ 1.475668  , -0.00767523]],

        [[-1.7058024 ,  1.0971006 ]]]], dtype=float32)>

In [129]:
# tf.expand_dim 增加一个维度, 如果axis 是正数就表示在该维度之前增加一个维度；如果axis是负数，表示在该维度之后增加一个维度
a=np.random.randint(0,100,size=(4,35,8))
print(a.shape)

(4, 35, 8)


In [130]:
# 在第0维之前增加一个维度
a0=tf.expand_dims(a,axis=0)
print(a0.shape)

(1, 4, 35, 8)


In [131]:
# 在第一维之前增加一个维度
a1=tf.expand_dims(a,axis=1)
print(a1.shape)

(4, 1, 35, 8)


In [132]:
# 在倒数第二维之后增加一个维度
a2=tf.expand_dims(a,axis=-2)
print(a2.shape)

(4, 35, 1, 8)


In [133]:
# tf.squeeze 减少一个shape为1的维度
tf.squeeze(a0).shape

TensorShape([4, 35, 8])

In [134]:
a=tf.zeros([1,2,1,1,3])

In [137]:
# 当有多个 shape=1的维度时
tf.squeeze(a)
# 可以指定要删除维度的轴
tf.squeeze(a,axis=2)

<tf.Tensor: id=878, shape=(1, 2, 1, 3), dtype=float32, numpy=
array([[[[0., 0., 0.]],

        [[0., 0., 0.]]]], dtype=float32)>

## Broadcasting: 
--表示将数据在某一维度上复制，但是没有真正在内存中复制；而tf.tile实现在内存中的复制（小维度对齐，只有一个数时，默认是小维度）

In [138]:
a=tf.ones((2,3))
print(a)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [139]:
a0=tf.broadcast_to(a,[2,2,3]) # 利用broadcast 扩张数据，但是内存上没有变化
print(a0)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [144]:
a1=tf.expand_dims(a,axis=0) #先增加一个维度
print(a1)
a2=tf.tile(a1,[2,1,1]) #再在相应维度上复制
print(a2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


## 数学运算

In [145]:
b=tf.fill([2,2],2.0)
print(b)
a=tf.ones((2,2))
print(a)

tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [150]:
# a+b
c=a+b
print('a+b=',c)

# a-b
c=a-b
print('a-b=',c)

# a*b
c=a*b #element wise
print('a*b=',c)

#a/b
c=a/b
print('a/b=',c)

a+b= tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float32)
a-b= tf.Tensor(
[[-1. -1.]
 [-1. -1.]], shape=(2, 2), dtype=float32)
a*b= tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
a/b= tf.Tensor(
[[0.5 0.5]
 [0.5 0.5]], shape=(2, 2), dtype=float32)


In [151]:
# b//a 整除
c=b//a
print('b//a=',c)

# b%a 取余
c=b%a
print('b%a=',c)


b//a= tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
b%a= tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [161]:
# log--表示以e为底的对数
# 求 log_8(3)
c=tf.math.log(8.)/tf.math.log(3.)
print('log_{3}=',c)

# 求Log_100(10)
c=tf.math.log(100.)/tf.math.log(10.)
print('log_100(10)=',c)

log_{3}= tf.Tensor(1.8927892, shape=(), dtype=float32)
log_100(10)= tf.Tensor(2.0, shape=(), dtype=float32)


In [162]:
#b的3次方
c=tf.pow(b,3)
print('b的3次方',c)

b的3次方 tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [163]:
print(b**3)

tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [164]:
print(tf.sqrt(b))

tf.Tensor(
[[1.4142134 1.4142134]
 [1.4142134 1.4142134]], shape=(2, 2), dtype=float32)


In [166]:
np.random.randn(10)

array([ 1.02017205,  0.3835371 ,  0.05597138, -0.1287526 , -0.70844902,
        0.45087574,  0.59559153, -0.35225331,  0.04402014,  0.00653837])

In [167]:
tf.random.truncated_normal([2,3])

<tf.Tensor: id=972, shape=(2, 3), dtype=float32, numpy=
array([[ 0.65511507, -0.00633255, -0.16290481],
       [-0.8425884 ,  1.118067  , -0.42477474]], dtype=float32)>

In [ ]:
tf.random.t